#!/bin/sh

set -e

APP_PROFILE="usr.sbin.sssd"
APP_CONFFILE="/etc/apparmor.d/$APP_PROFILE"
APP_COMPLAIN="/etc/apparmor.d/force-complain/$APP_PROFILE"

inst_complain_profile() {
    # Create a symlink to the yet-to-be-unpacked profile
    mkdir -p `dirname $APP_COMPLAIN` 2>/dev/null || true
    ln -sf $APP_CONFFILE $APP_COMPLAIN
}

case "$1" in
install)
    # Force the AppArmor profile to complain mode on install
    inst_complain_profile
    ;;
esac

#DEBHELPER#
